[package]
name = "cdi-frontend"
description = "CD-i emulator desktop frontend (egui/eframe)"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
log.workspace = true
env_logger.workspace = true
eframe.workspace = true
egui.workspace = true
rfd.workspace = true
clap.workspace = true
cpal.workspace = true
rtrb.workspace = true
cdi-core = { path = "../cdi-core" }
cdi-disc = { path = "../cdi-disc" }
cdi-os9 = { path = "../cdi-os9" }

[lints]
workspace = true
