[package]
name = "cdi-frontend"
description = "E-Di: Emulator Disc Interactive desktop frontend (egui/eframe)"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
log.workspace = true
env_logger.workspace = true
png.workspace = true
eframe = { workspace = true, features = ["persistence"] }
egui.workspace = true
serde.workspace = true
serde_json.workspace = true
rfd.workspace = true
clap.workspace = true
cpal.workspace = true
gilrs.workspace = true
rtrb.workspace = true
cdi-core = { path = "../cdi-core" }
cdi-disc = { path = "../cdi-disc" }
cdi-os9 = { path = "../cdi-os9" }

[target.'cfg(target_os = "macos")'.dependencies]
muda.workspace = true

[lints]
workspace = true
